#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Bradley C. Love

# Short bio or description (displayed in the header)
description: I am Professor of Cognitive and Decision Sciences in Experimental Psychology at UCL and a fellow at The Alan Turing Institute for data science. My lab's research centers around human learning and decision making, integrating behavioural, computational, and neuroscience perspectives.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar:

#
# Flags below are optional
#

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: bradlove-1

twitter: ProfData

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-78483005-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://bradlove.org

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /blog/:title


# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME

collections:
  people:

array: []
